version: "3.8"

services:
  convertion-tool-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: cerely -A tareas worker -l info
    environment:
      DB_HOST: "db"
    ports:
      - "8000:5000"
    links:
      - redis-server
    depends_on:
      - db
      - redis-server

  db:
    image: postgres
    environment:
      - POSTGRES_DB=conversion_tool
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"

  redis-server:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./
    hostname: worker
    entrypoint: celery
    command: -A tareas worker --loglevel=info -B
    volumes:
      - ./:/worker-info
    links:
      - redis-server
    depends_on:
      - redis-server